[workspace]
members = [
    # Main libraries
    "neurs",            # core
    "styliso",          # image style distinction
    "cnmc",             # sentence generator

    # Demo programs
    "cnmc_console"      # cnmc demo (conversation console)
]
