[workspace]
members = [
    # Main libraries
    "neurs",            # core
    "styliso",          # image style distinction
    "cmnc",             # sentence generator

    # Demo programs
    "cmnc_console"      # cmnc demo (conversation console)
]
